/**
 * Every user-visible string in SVNpush. Short, factual, second person.
 * Buttons are verbs. No exclamation marks.
 */
import { HELP } from "./helpStrings";
import { TOOLS } from "./toolStrings";

export const S = {
  help: HELP,
  tools: TOOLS,
  app: {
    name: "SVNpush",
  },
  nav: {
    label: "Main",
    projects: "Projects",
    release: "Release",
    providers: "Providers",
    vault: "Vault",
    settings: "Settings",
    help: "Help",
  },
  theme: {
    label: "Theme",
    system: "System",
    light: "Light",
    dark: "Dark",
  },
  common: {
    cancel: "Cancel",
    save: "Save",
    remove: "Remove",
    close: "Close",
    copy: "Copy",
    copied: "Copied",
    loading: "Loading…",
    none: "None",
    fix: "Fix",
    yes: "Yes",
    no: "No",
  },
  projects: {
    title: "Projects",
    subtitle: "Your WordPress plugins. Open one to release it.",
    add: "Add project",
    emptyTitle: "No projects yet",
    emptyBody:
      "Add a plugin folder to start. SVNpush reads its header and readme, then asks for the SVN URL.",
    columns: {
      name: "Plugin",
      version: "Version",
      lastRelease: "Last release",
    },
    open: "Open",
    neverReleased: "Not released yet",
    unfinished: "Unfinished release",
    locked: "Releasing in another window",
    addTitle: "Add a project",
    chooseFolder: "Choose folder",
    folder: "Plugin folder",
    folderHint: "The folder that holds the main plugin file.",
    svnUrl: "SVN URL",
    svnUrlHint: "The slug at the end of this URL is the plugin's WordPress.org slug.",
    mainFile: "Main plugin file",
    mainFileHint: "More than one PHP file has a Plugin Name header. Choose the plugin's own.",
    detected: (name: string, version: string) => `${name}, version ${version}`,
    noMainFile: "No PHP file in this folder has a Plugin Name header.",
  },
  outcome: {
    Complete: "Published",
    PublishedUnverified: "Published, unverified",
    DryRun: "Dry run",
    Failed: "Failed",
    Cancelled: "Cancelled",
  },
  release: {
    title: "Release",
    subtitle: "Open a project to release it.",
    emptyTitle: "No project open",
    emptyBody: "Open a project from Projects to release it.",
    release: "Release",
    dryRun: "Dry run",
    dryRunHint: "Stops after the SVN preview. Nothing is committed and your files are restored.",
    assets: "Update assets",
    assetsHint:
      "Sync and commit only your assets folder: banners, icons and screenshots. No version change and no tag.",
    assetsPublished: "Assets published",
    cancel: "Cancel",
    running: "Release in progress",
    svnUrl: "SVN URL",
    account: "Account",
    noAccount: "No SVN account in Vault",
    version: "Version",
    interrupted: (step: number) => `A release was interrupted at step ${step}.`,
    needsTag: (version: string) =>
      `Trunk was committed for ${version} but the tag was not created.`,
    resume: "Resume",
    resumeTag: "Resume: create tag",
    discard: "Discard",
    notices: "Notes",
    resetWorkingCopy: "Reset working copy",
    resetDone: "The working copy was checked out again.",
    openHelp: "Open Help",
    phase: {
      Idle: "Starting",
      Detecting: "Detecting",
      Drafting: "Drafting the release notes",
      AwaitingApproval: "Waiting for your draft",
      Writing: "Writing",
      Verifying: "Verifying",
      AwaitingFixes: "Waiting for fixes",
      Building: "Building",
      AwaitingFileReview: "Waiting for you to check the files",
      Previewing: "Preparing the SVN preview",
      AwaitingPublish: "Waiting for your confirmation",
      Publishing: "Publishing",
      Verified: "Published and verified",
      PublishedUnverified: "Published, not yet verified",
      DryRunComplete: "Dry run complete",
      Failed: "Failed",
      Cancelled: "Cancelled",
    },
  },
  steps: {
    Detect: "Detect",
    Draft: "Changes and draft",
    Write: "Write",
    Verify: "Verify",
    Build: "Build",
    Preview: "Preview SVN",
    Publish: "Publish",
    status: {
      Pending: "Pending",
      Running: "Running",
      Waiting: "Waiting for you",
      Done: "Done",
      Failed: "Failed",
      Skipped: "Skipped",
    },
    expand: "Show details",
    collapse: "Hide details",
  },
  detect: {
    mainFile: "Main file",
    slug: "Slug",
    textDomain: "Text Domain",
    previous: "Previous release",
    firstRelease: "None, this is the first release",
    tags: "Tags on the server",
    versions: "Version sources",
    missing: "missing",
    git: "Git",
    branch: (branch: string) => `branch ${branch}`,
    dirty: (count: number) => `${count} uncommitted change(s)`,
    noGit: "Not a git repository, or git is not installed",
  },
  changes: {
    title: "What changed",
    sourceGit: (base: string) => `Compared with git tag ${base}, including uncommitted changes.`,
    sourceTrunk: "Compared with trunk on the server.",
    sourceFirst: "Trunk is empty: everything is new.",
    sourceUnknown:
      "The package root is created by the pre-build command, so changes are shown after Build.",
    commits: "Commits",
    kind: { Added: "Added", Modified: "Modified", Deleted: "Deleted" },
    none: "No files listed.",
  },
  draft: {
    title: "Draft",
    version: "Version",
    versionHint: (previous: string | null) =>
      previous ? `The previous release is ${previous}.` : "This is the first release.",
    changelog: "Changelog entry",
    changelogHint: "Written under == Changelog == in readme.txt. Use * for list items.",
    upgradeNotice: "Upgrade notice",
    upgradeNoticeHint:
      "Optional. Shown on the WordPress.org plugin page and in the updates screen.",
    approve: "Approve",
    approved: (version: string) => `Version ${version} approved.`,
    reason: (reason: string) => `Why this version: ${reason}`,
    summary: "Release summary",
    summaryHint:
      "One paragraph about the release, for your announcement. It is not written to any file.",
  },
  ai: {
    draftTitle: "AI draft",
    explainTitle: "Why the checks failed",
    off: "AI is off for this project. Write the release notes below.",
    working: (label: string) => `Asking ${label}…`,
    queued: (position: number | null) =>
      position === null
        ? "Waiting in the Revoye queue."
        : `Waiting in the Revoye queue, position ${String(position)}.`,
    jobStatus: (status: string) => `Revoye job ${status}.`,
    fleet: (online: number, total: number, idle: number, waiting: number) =>
      `${String(online)} of ${String(total)} device(s) online · ${String(idle)} agent(s) free · ${String(waiting)} job(s) waiting`,
    startDesk:
      "No device is online. Start Revoye Desk on your machine; the job stays queued until then.",
    summaries: (done: number, total: number) =>
      `Summarising changed files first: ${String(done)} of ${String(total)}.`,
    fromSummaries: "The diff was too large, so this draft was written from per-file summaries.",
    drafted: (label: string) => `Drafted by ${label}. Edit anything before you approve.`,
    explained: (label: string) => `Explained by ${label}.`,
    fellBack: (from: string) =>
      `${from} failed, so the next provider in your fallback order answered.`,
    manual: "You are writing this by hand.",
    stop: "Stop and write it myself",
    stopExplaining: "Stop",
    writeMyself: "Write it myself",
    askAi: "Draft with AI",
    explainAgain: "Explain with AI",
    regenerate: "Regenerate",
    retry: "Retry",
    change: "Change",
    changeLabel: "AI provider for this run",
    use: "Use",
    openProviders: "Open Providers",
    rawText: "The AI's answer, which could not be used:",
    privacyTitle: "Before the AI sees your plugin",
    privacyIntro: (label: string) =>
      `SVNpush is about to send project data to ${label}. This notice appears once for each provider.`,
    privacySends: [
      "Diffs of changed files, except files your exclude patterns match and files that look like secrets (.env, *.pem, *.key, wp-config.php)",
      "Commit subjects since the previous release",
      "Recent changelog entries and, when checks fail, readme.txt",
      "The start of the main plugin file and the failed check messages, when checks fail",
      "The plugin name, slug and versions",
    ],
    privacyNever:
      "Passwords, API keys and SVN credentials are never sent. The AI never runs commands or writes files: you approve everything it suggests.",
    privacyRevoye:
      "With Revoye, answers come from AI accounts you are already signed into, through Revoye Desk on your own machine.",
    privacyAccept: "Send and continue",
    fixesTitle: "Suggested readme fixes",
    fixFor: (checkId: string) => `Fixes ${checkId}`,
    applyFixes: "Apply selected fixes and check again",
    stopRelease: "Stop the release",
    noFixes: "No readme edit applies. Fix the failed checks yourself, then release again.",
    cannotApply: "Cannot be applied:",
  },
  write: {
    none: "No files needed changes.",
  },
  checks: {
    blocking: "Blocking checks",
    warnings: "Warnings",
    status: { Pass: "Pass", Fail: "Fail", Skip: "Skip" },
    none: "Checks run after the draft is written.",
  },
  build: {
    files: "Files",
    size: "Size",
    total: (count: number, size: string) => `${count} file(s), ${size}`,
    zip: "Zip",
    checksum: "SHA-256",
    reveal: "Show zip",
    copyPath: "Copy zip path",
  },
  files: {
    title: "Check the files to release",
    reason: {
      NoDistignore:
        "Your plugin has no .distignore yet. SVNpush suggests one below: hidden files and developer-only files are left out.",
      FirstRelease: "This is the first release, so every file below goes to WordPress.org.",
      NewItems:
        "Some files or folders were not in the last release. Check they belong in the plugin.",
    },
    summary: (count: number, size: string, left: number) =>
      `${String(count)} file(s), ${size}, will be released · ${String(left)} left out`,
    released: "Will be released",
    leftOut: "Left out",
    fileCount: (count: number) => `${String(count)} file(s)`,
    more: (count: number) => `and ${String(count)} more`,
    newBadge: "New",
    rules: "Rules (.distignore)",
    rulesHint:
      "One pattern per line, like .gitignore. A leading / means the plugin folder; lines starting with # are notes. Saved in your plugin folder: commit it with your code.",
    builtByCommand:
      "These files come from your pre-build command, so change that command to change them.",
    updating: "Updating the list…",
    save: "Save .distignore and continue",
    confirm: "The files are right, continue",
  },
  preview: {
    trunk: "trunk/",
    assets: "assets/",
    added: "Added",
    modified: "Modified",
    deleted: "Deleted",
    nothing: "No changes.",
    tagUrl: "Tag to create",
    trunkMessage: "Trunk commit message",
    tagMessage: "Tag commit message",
    diffTitle: (path: string) => `Diff of ${path}`,
    showDiff: "Show diff",
    hideDiff: "Hide diff",
  },
  publish: {
    publish: "Publish",
    confirmTitle: "Publish this release",
    confirmBody:
      "This commits trunk and creates the tag on WordPress.org. After the trunk commit it cannot be undone.",
    version: "Version",
    slug: "Slug",
    svnUrl: "SVN URL",
    account: "Account",
    counts: (trunk: string, assets: string) => `trunk ${trunk} · assets ${assets}`,
    trunkRevision: "Trunk revision",
    tagRevision: "Tag revision",
    unchanged: "unchanged",
    verified: "The tag is on the server and its readme names this version.",
    unverified: (reason: string) => `The tag could not be verified yet: ${reason}`,
    openPage: "Open plugin page",
    assetsMessage: "Assets commit message",
    assetsTitle: "Publish these assets",
    assetsBody: "This commits assets/ on WordPress.org. Trunk and tags are not touched.",
    assetsRevision: "Assets revision",
  },
  log: {
    title: "Log",
    show: "Show log",
    hide: "Hide log",
    empty: "Command output appears here while a release runs.",
    copy: "Copy log",
  },
  history: {
    title: "Past releases",
    assets: "Assets",
    empty: "No releases yet.",
    date: "Started",
    version: "Version",
    result: "Result",
    revisions: "Revisions",
    dryRun: "dry run",
  },
  projectSettings: {
    title: "Project settings",
    svnUrl: "SVN URL",
    packageRoot: "Package root",
    packageRootHint: "Leave empty to package the project folder, or name a subfolder such as dist.",
    mainFile: "Main plugin file",
    mainFileHint: "Leave empty to detect it.",
    versionLocations: "Extra version locations",
    versionLocationsHint:
      "A file and a regular expression with one capture group around the version, for example define\\(\\s*'MY_VERSION',\\s*'([^']+)'",
    locationPath: "File",
    locationPattern: "Pattern",
    addLocation: "Add location",
    requiredPaths: "Required paths",
    requiredPathsHint: "One per line. The main file and readme.txt are always required.",
    preBuild: "Pre-build command",
    preBuildHint:
      "Runs in the project folder before Build, for example npm run build. Shown in the log before it runs.",
    assetsFolder: "Assets folder",
    assetsFolderHint: "Leave empty to use .wordpress-org when it exists.",
    noAssets: "Do not sync an assets folder",
    allowPhar: "Allow .phar files in the package",
    gitTag: "After publishing, commit the release edits and create git tag v<version>",
    openPage: "After publishing, open the plugin page",
    svnAccount: "SVN account",
    svnAccountHint: "The Vault username to commit as. Leave empty to use the only account.",
    aiProvider: "AI provider",
    aiProviderHint:
      "Which AI writes the draft and explains failed checks. You can change it for one run from the Draft step.",
    aiDefault: "The default provider",
    aiPinned: (label: string) => `Always ${label}`,
    aiOff: "Off: write release notes by hand",
    aiExclude: "AI exclude patterns",
    aiExcludeHint:
      "One .gitignore-style pattern per line. Matching files never reach the AI. Files that look like secrets are always kept out.",
    saved: "Settings saved.",
    removeProject: "Remove project",
    removeTitle: "Remove this project",
    removeBody:
      "SVNpush forgets this project. Your plugin folder, its working copy and past run journals stay on disk.",
  },
  providers: {
    title: "AI Providers",
    subtitle: "Connect the AI that writes your release notes. You choose which runs, always.",
    add: "Add provider",
    emptyTitle: "No AI providers yet",
    emptyBody:
      "No AI providers yet. Revoye is recommended. A local model works without an API key.",
    defaultBadge: "Default",
    needsAttention: (why: string) => `Needs attention: ${why}`,
    requests: (count: number) => `${count.toString()} request(s) this month`,
    test: "Test",
    setDefault: "Set as default",
    edit: "Edit",
    remove: "Remove",
    clear: "Clear",
    removeTitle: "Remove this provider",
    removeBody: (label: string) =>
      `SVNpush forgets ${label} and deletes its API key from your keychain.`,
    formAdd: "Add provider",
    formEdit: "Edit provider",
    provider: "Provider",
    recommended: " (Recommended)",
    label: "Label",
    labelPlaceholder: "Name this provider",
    model: "Model",
    loadModels: "Load the models this account can use",
    loadingModels: "Loading models…",
    modelsLoaded: (count: number) => `${count.toString()} model(s) enabled on this account.`,
    apiKey: "API key",
    keyUnchanged: "Unchanged — paste a new key to replace it",
    keyHint: "Stored in your operating system keychain. Never written to a file.",
    showKey: "Show API key",
    hideKey: "Hide API key",
    pasteKeyFirst: "Paste the API key first. The key names the account.",
    advanced: "Advanced",
    baseUrl: "Base URL",
    baseUrlHint: "Only change this for self-hosted gateways or local servers.",
    defaultToggle: "Use this provider when nothing else is chosen",
    save: "Save",
    saved: "Provider saved.",
    fleetNoDevice: (total: number) =>
      `No device online, ${total.toString()} paired. Jobs wait until one connects.`,
    fleetOnline: (online: number, total: number, idle: number, agents: number, queued: number) =>
      `${online.toString()} of ${total.toString()} device(s) online · ${idle.toString()} of ${agents.toString()} agents free` +
      (queued > 0 ? ` · ${queued.toString()} job(s) queued` : ""),
    agentsFree: (count: number) => ` — ${count.toString()} agent(s) free`,
    agentsBusy: " — all agents busy",
    disabledKind: " — disabled",
    fallbackTitle: "Automatic fallback",
    fallbackBody:
      "Off by default. When a provider fails with a bad key, a rate limit or an outage, SVNpush normally tells you rather than quietly using a different AI. Tick providers below to let it roll over to them instead, in this order.",
    moveUp: "Move up",
    moveDown: "Move down",
    saveFallback: "Save fallback order",
    fallbackSaved: (count: number) =>
      count > 0
        ? `Fallback saved: ${count.toString()} provider(s) in order.`
        : "Fallback is off. Failures will be shown instead of switching AI.",
  },
  vault: {
    title: "Vault",
    subtitle: "SVN accounts, stored in your operating system keychain.",
    reminder:
      "Use the SVN password from your WordPress.org profile (Account & Security → Subversion password), not your account password. WordPress.org requires it for committers with two-factor authentication.",
    emptyTitle: "No SVN accounts yet",
    emptyBody: "Add your WordPress.org username and SVN password to publish releases.",
    host: "Host",
    username: "Username",
    password: "SVN password",
    passwordPlaceholderNew: "Paste the SVN password",
    passwordPlaceholderExisting: "Unchanged — paste a new password to replace it",
    passwordHint: "Stored in your operating system keychain. Never written to a file.",
    showPassword: "Show password",
    hidePassword: "Hide password",
    edit: "Change password",
    add: "Add account",
    save: "Save account",
    test: "Test",
    remove: "Remove",
    stored: "Password stored",
    missing: "No password stored",
    removeTitle: "Forget this account",
    removeBody: (username: string) =>
      `SVNpush forgets ${username} and deletes its password from your keychain.`,
  },
  settings: {
    title: "Settings",
    subtitle: "Appearance, tools and privacy.",
    appearance: "Appearance",
    theme: "Theme",
    tools: "Tools",
    svnPath: "svn executable",
    gitPath: "git executable",
    pathHint: "Leave empty to search PATH and the usual install locations.",
    doctor: "Run Doctor",
    keychain: "Keychain",
    keychainOk: "Available.",
    found: "Found",
    notFound: "Not found",
    privacy: "Privacy",
    wordpressLookup: "Check the current WordPress version on api.wordpress.org (warning W02)",
    wordpressLookupHint: "Only the version number is fetched, at most once a day.",
    save: "Save settings",
    saved: "Settings saved.",
    diagnostics: "Diagnostics",
    diagnosticsHint:
      "Copies the app version, Doctor results, settings and the end of the latest log, with secrets removed, for a bug report.",
    copyDiagnostics: "Copy diagnostics",
    about: "About",
    version: (version: string) => `SVNpush ${version}`,
    checkUpdate: "Check for updates",
    upToDate: "You have the latest version.",
    updateAvailable: (version: string) => `Version ${version} is available.`,
    installUpdate: "Install and restart",
  },
  errors: {
    unexpected: "Something went wrong.",
  },
} as const;
