/**
 * Every user-visible string in SVNpush. Short, factual, second person.
 * Buttons are verbs. No exclamation marks.
 */
export const S = {
  app: {
    name: "SVNpush",
  },
  nav: {
    label: "Main",
    projects: "Projects",
    release: "Release",
    providers: "Providers",
    vault: "Vault",
    settings: "Settings",
  },
  theme: {
    label: "Theme",
    system: "System",
    light: "Light",
    dark: "Dark",
  },
  common: {
    cancel: "Cancel",
    save: "Save",
    remove: "Remove",
    close: "Close",
    copy: "Copy",
    copied: "Copied",
    loading: "Loading…",
    none: "None",
    fix: "Fix",
    yes: "Yes",
    no: "No",
  },
  projects: {
    title: "Projects",
    subtitle: "Your WordPress plugins. Open one to release it.",
    add: "Add project",
    emptyTitle: "No projects yet",
    emptyBody:
      "Add a plugin folder to start. SVNpush reads its header and readme, then asks for the SVN URL.",
    columns: {
      name: "Plugin",
      version: "Version",
      lastRelease: "Last release",
    },
    open: "Open",
    neverReleased: "Not released yet",
    unfinished: "Unfinished release",
    locked: "Releasing in another window",
    addTitle: "Add a project",
    chooseFolder: "Choose folder",
    folder: "Plugin folder",
    folderHint: "The folder that holds the main plugin file.",
    svnUrl: "SVN URL",
    svnUrlHint: "The slug at the end of this URL is the plugin's WordPress.org slug.",
    mainFile: "Main plugin file",
    mainFileHint: "More than one PHP file has a Plugin Name header. Choose the plugin's own.",
    detected: (name: string, version: string) => `${name}, version ${version}`,
    noMainFile: "No PHP file in this folder has a Plugin Name header.",
  },
  outcome: {
    Complete: "Published",
    PublishedUnverified: "Published, unverified",
    DryRun: "Dry run",
    Failed: "Failed",
    Cancelled: "Cancelled",
  },
  release: {
    title: "Release",
    subtitle: "Open a project to release it.",
    emptyTitle: "No project open",
    emptyBody: "Open a project from Projects to release it.",
    release: "Release",
    dryRun: "Dry run",
    dryRunHint: "Stops after the SVN preview. Nothing is committed and your files are restored.",
    cancel: "Cancel",
    running: "Release in progress",
    svnUrl: "SVN URL",
    account: "Account",
    noAccount: "No SVN account in Vault",
    version: "Version",
    interrupted: (step: number) => `A release was interrupted at step ${step}.`,
    needsTag: (version: string) =>
      `Trunk was committed for ${version} but the tag was not created.`,
    resume: "Resume",
    resumeTag: "Resume: create tag",
    discard: "Discard",
    notices: "Notes",
    resetWorkingCopy: "Reset working copy",
    resetDone: "The working copy was checked out again.",
    phase: {
      Idle: "Starting",
      Detecting: "Detecting",
      Drafting: "Reading changes",
      AwaitingApproval: "Waiting for your draft",
      Writing: "Writing",
      Verifying: "Verifying",
      Building: "Building",
      Previewing: "Preparing the SVN preview",
      AwaitingPublish: "Waiting for your confirmation",
      Publishing: "Publishing",
      Verified: "Published and verified",
      PublishedUnverified: "Published, not yet verified",
      DryRunComplete: "Dry run complete",
      Failed: "Failed",
      Cancelled: "Cancelled",
    },
  },
  steps: {
    Detect: "Detect",
    Draft: "Changes and draft",
    Write: "Write",
    Verify: "Verify",
    Build: "Build",
    Preview: "Preview SVN",
    Publish: "Publish",
    status: {
      Pending: "Pending",
      Running: "Running",
      Waiting: "Waiting for you",
      Done: "Done",
      Failed: "Failed",
      Skipped: "Skipped",
    },
    expand: "Show details",
    collapse: "Hide details",
  },
  detect: {
    mainFile: "Main file",
    slug: "Slug",
    textDomain: "Text Domain",
    previous: "Previous release",
    firstRelease: "None, this is the first release",
    tags: "Tags on the server",
    versions: "Version sources",
    missing: "missing",
    git: "Git",
    branch: (branch: string) => `branch ${branch}`,
    dirty: (count: number) => `${count} uncommitted change(s)`,
    noGit: "Not a git repository, or git is not installed",
  },
  changes: {
    title: "What changed",
    sourceGit: (base: string) => `Compared with git tag ${base}, including uncommitted changes.`,
    sourceTrunk: "Compared with trunk on the server.",
    sourceFirst: "Trunk is empty: everything is new.",
    sourceUnknown:
      "The package root is created by the pre-build command, so changes are shown after Build.",
    commits: "Commits",
    kind: { Added: "Added", Modified: "Modified", Deleted: "Deleted" },
    none: "No files listed.",
  },
  draft: {
    title: "Draft",
    version: "Version",
    versionHint: (previous: string | null) =>
      previous ? `The previous release is ${previous}.` : "This is the first release.",
    changelog: "Changelog entry",
    changelogHint: "Written under == Changelog == in readme.txt. Use * for list items.",
    upgradeNotice: "Upgrade notice",
    upgradeNoticeHint:
      "Optional. Shown on the WordPress.org plugin page and in the updates screen.",
    approve: "Approve",
    approved: (version: string) => `Version ${version} approved.`,
    manual: "Written by hand",
  },
  write: {
    none: "No files needed changes.",
  },
  checks: {
    blocking: "Blocking checks",
    warnings: "Warnings",
    status: { Pass: "Pass", Fail: "Fail", Skip: "Skip" },
    none: "Checks run after the draft is written.",
  },
  build: {
    files: "Files",
    size: "Size",
    total: (count: number, size: string) => `${count} file(s), ${size}`,
    zip: "Zip",
    checksum: "SHA-256",
    reveal: "Show zip",
    copyPath: "Copy zip path",
  },
  preview: {
    trunk: "trunk/",
    assets: "assets/",
    added: "Added",
    modified: "Modified",
    deleted: "Deleted",
    nothing: "No changes.",
    tagUrl: "Tag to create",
    trunkMessage: "Trunk commit message",
    tagMessage: "Tag commit message",
    diffTitle: (path: string) => `Diff of ${path}`,
    showDiff: "Show diff",
    hideDiff: "Hide diff",
  },
  publish: {
    publish: "Publish",
    confirmTitle: "Publish this release",
    confirmBody:
      "This commits trunk and creates the tag on WordPress.org. After the trunk commit it cannot be undone.",
    version: "Version",
    slug: "Slug",
    svnUrl: "SVN URL",
    account: "Account",
    counts: (trunk: string, assets: string) => `trunk ${trunk} · assets ${assets}`,
    trunkRevision: "Trunk revision",
    tagRevision: "Tag revision",
    unchanged: "unchanged",
    verified: "The tag is on the server and its readme names this version.",
    unverified: (reason: string) => `The tag could not be verified yet: ${reason}`,
    openPage: "Open plugin page",
  },
  log: {
    title: "Log",
    show: "Show log",
    hide: "Hide log",
    empty: "Command output appears here while a release runs.",
    copy: "Copy log",
  },
  history: {
    title: "Past releases",
    empty: "No releases yet.",
    date: "Started",
    version: "Version",
    result: "Result",
    revisions: "Revisions",
    dryRun: "dry run",
  },
  projectSettings: {
    title: "Project settings",
    svnUrl: "SVN URL",
    packageRoot: "Package root",
    packageRootHint: "Leave empty to package the project folder, or name a subfolder such as dist.",
    mainFile: "Main plugin file",
    mainFileHint: "Leave empty to detect it.",
    versionLocations: "Extra version locations",
    versionLocationsHint:
      "A file and a regular expression with one capture group around the version, for example define\\(\\s*'MY_VERSION',\\s*'([^']+)'",
    locationPath: "File",
    locationPattern: "Pattern",
    addLocation: "Add location",
    requiredPaths: "Required paths",
    requiredPathsHint: "One per line. The main file and readme.txt are always required.",
    preBuild: "Pre-build command",
    preBuildHint:
      "Runs in the project folder before Build, for example npm run build. Shown in the log before it runs.",
    assetsFolder: "Assets folder",
    assetsFolderHint: "Leave empty to use .wordpress-org when it exists.",
    noAssets: "Do not sync an assets folder",
    allowPhar: "Allow .phar files in the package",
    gitTag: "After publishing, commit the release edits and create git tag v<version>",
    openPage: "After publishing, open the plugin page",
    svnAccount: "SVN account",
    svnAccountHint: "The Vault username to commit as. Leave empty to use the only account.",
    saved: "Settings saved.",
    removeProject: "Remove project",
    removeTitle: "Remove this project",
    removeBody:
      "SVNpush forgets this project. Your plugin folder, its working copy and past run journals stay on disk.",
  },
  providers: {
    title: "AI Providers",
    subtitle: "Connect the AI that writes your release notes. You choose which runs, always.",
  },
  vault: {
    title: "Vault",
    subtitle: "SVN accounts, stored in your operating system keychain.",
  },
  settings: {
    title: "Settings",
    subtitle: "Appearance, tools and privacy.",
  },
  errors: {
    unexpected: "Something went wrong.",
  },
} as const;
